# Generated by Django 5.1.3 on 2024-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interest_images/'),
        ),
    ]
