# Generated by Django 5.1.3 on 2024-11-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_interest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
