# Generated by Django 5.1.3 on 2024-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('feedback', 'Feedback'), ('questions', 'Questions')], default='services', max_length=20),
        ),
    ]
