# Generated by Django 5.1.3 on 2024-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutMyself', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='title',
        ),
        migrations.AddField(
            model_name='interest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interests/'),
        ),
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(default='Default Interest', max_length=100),
        ),
    ]
