# Generated by Django 5.1.3 on 2024-11-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
